import type { Metadata } from 'next'
import './globals.css'
import { Vazirmatn } from 'next/font/google'
import ReactQueryProvider from '@/providers/react-query'
import Footer from '@/components/shared/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const vazir = Vazirmatn({
  subsets: ['latin'],
  weight: ['400', '700']
})
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fa' dir='rtl' className={`${vazir.className}`}>
      <body className='flex h-dvh max-h-dvh flex-col overflow-auto'>
        <ReactQueryProvider>
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
